"""
Dataset registry mirroring the 13 US GHG Center / NASA datasets named in the
project blueprint. This is metadata only (provider, role, resolution, provenance) —
no raw rasters are stored here or in MongoDB, per the blueprint's guardrail.

NOTE ON DATA REALISM: this build ships without live connectivity to the NASA
Earthdata / US GHG Center archives (multi-GB granules, auth-gated, out of scope
for this environment). Every numeric value the API returns is generated by
`app/data/synthetic.py`, a procedural model that is physically *structured*
(driven by land-cover, wetland, population and NDVI-like proxies with
realistic magnitudes) but is NOT the ingested satellite product. This is
labeled everywhere in the API responses and UI as representative/demo data.
See docs/limitations.md.
"""

from app.db.schemas import Dataset

DATASETS: list[Dataset] = [
    Dataset(
        dataset_id="oco2-geos-co2",
        name="OCO-2 GEOS Column CO2",
        provider="NASA GES DISC",
        role="Atmospheric / top-down context",
        variable="CO2",
        resolution="Daily global; 0.5 x 0.625 deg",
        time_range="2015-present",
        provenance="Observed",
    ),
    Dataset(
        dataset_id="oco2-mip-topdown",
        name="OCO-2 MIP Top-down CO2 Budgets",
        provider="NASA / Global Carbon Project MIP",
        role="CO2 source/sink target + conservation reference",
        variable="CO2",
        resolution="Annual 1 deg; 2015-2020",
        time_range="2015-2020",
        provenance="Modeled",
    ),
    Dataset(
        dataset_id="odiac-ffco2",
        name="ODIAC Fossil Fuel CO2",
        provider="NIES / Tohoku University",
        role="Fine fossil-fuel prior",
        variable="CO2",
        resolution="Monthly global 1 km",
        time_range="2000-present",
        provenance="Modeled",
    ),
    Dataset(
        dataset_id="micasa-flux",
        name="MiCASA Land Carbon Flux",
        provider="NASA GSFC",
        role="Natural carbon source/sink features",
        variable="CO2",
        resolution="Daily/monthly 0.1 deg",
        time_range="2000-present",
        provenance="Modeled",
    ),
    Dataset(
        dataset_id="lpj-eosim-ch4",
        name="LPJ-EOSIM Wetland CH4",
        provider="US GHG Center",
        role="Wetland methane target/prior",
        variable="CH4",
        resolution="Daily/monthly 0.5 deg",
        time_range="2000-2021",
        provenance="Modeled",
    ),
    Dataset(
        dataset_id="ecco-darwin-co2",
        name="ECCO-Darwin Air-Sea CO2 Flux",
        provider="NASA JPL",
        role="Ocean sink layer",
        variable="CO2",
        resolution="~1/3 deg monthly; 2020-2022",
        time_range="2020-2022",
        provenance="Modeled",
    ),
    Dataset(
        dataset_id="gosat-ch4-budgets",
        name="GOSAT-based CH4 Budgets",
        provider="JAXA / NIES",
        role="Top-down methane totals + categories",
        variable="CH4",
        resolution="1 deg; 2019",
        time_range="2019",
        provenance="Modeled",
    ),
    Dataset(
        dataset_id="tm5-4dvar-ch4",
        name="TM5-4DVar CH4 Fluxes",
        provider="SRON / Global Carbon Project",
        role="Independent methane source classes",
        variable="CH4",
        resolution="Monthly 1 deg",
        time_range="2000-present",
        provenance="Modeled",
    ),
    Dataset(
        dataset_id="emit-plumes",
        name="EMIT CH4 Plume Complexes",
        provider="NASA JPL",
        role="Large methane event evidence",
        variable="CH4",
        resolution="Plume observations (~60m)",
        time_range="2022-present",
        provenance="Observed",
    ),
    Dataset(
        dataset_id="noaa-surface",
        name="NOAA CO2 / CH4 Surface Network",
        provider="NOAA GML",
        role="Long-term atmospheric context",
        variable="CO2",
        resolution="Surface observations",
        time_range="1970-present",
        provenance="Observed",
    ),
    Dataset(
        dataset_id="us-anthro-ch4",
        name="U.S. Anthropogenic CH4",
        provider="EPA / US GHG Center",
        role="Detailed human methane layer",
        variable="CH4",
        resolution="0.1 deg annual, U.S.",
        time_range="2012-2020",
        provenance="Modeled",
    ),
    Dataset(
        dataset_id="population-density",
        name="Gridded Population of the World",
        provider="NASA SEDAC",
        role="Exposure / population weighting",
        variable="CO2",
        resolution="~1 km; 2000-2020",
        time_range="2000-2020",
        provenance="Observed",
    ),
]


def get_dataset(dataset_id: str) -> Dataset | None:
    return next((d for d in DATASETS if d.dataset_id == dataset_id), None)
